frr version 9.0
frr defaults traditional
hostname tgw
no ipv6 forwarding
!
router bgp 64512
 bgp router-id 10.200.0.2
 neighbor 10.200.0.1 remote-as 64512
 neighbor 10.200.0.1 description AWS-Edge
 neighbor 10.200.0.1 update-source eth1
 neighbor 10.200.1.2 remote-as 64512
 neighbor 10.200.1.2 description VPC-A-GW
 neighbor 10.200.1.2 update-source eth2
 neighbor 10.200.2.2 remote-as 64512
 neighbor 10.200.2.2 description VPC-B-GW
 neighbor 10.200.2.2 update-source eth3
 neighbor 10.200.3.2 remote-as 64512
 neighbor 10.200.3.2 description VPC-C-GW
 neighbor 10.200.3.2 update-source eth4
 !
 address-family ipv4 unicast
  neighbor 10.200.0.1 activate
  neighbor 10.200.0.1 next-hop-self
  neighbor 10.200.0.1 soft-reconfiguration inbound
  neighbor 10.200.0.1 route-reflector-client
  neighbor 10.200.1.2 activate
  neighbor 10.200.1.2 next-hop-self
  neighbor 10.200.1.2 soft-reconfiguration inbound
  neighbor 10.200.1.2 route-reflector-client
  neighbor 10.200.2.2 activate
  neighbor 10.200.2.2 next-hop-self
  neighbor 10.200.2.2 soft-reconfiguration inbound
  neighbor 10.200.2.2 route-reflector-client
  neighbor 10.200.3.2 activate
  neighbor 10.200.3.2 next-hop-self
  neighbor 10.200.3.2 soft-reconfiguration inbound
  neighbor 10.200.3.2 route-reflector-client
 exit-address-family
!
line vty
