frr version 9.0
frr defaults traditional
hostname vpc-a-gw
no ipv6 forwarding
!
router bgp 64512
 bgp router-id 10.200.1.2
 neighbor 10.200.1.1 remote-as 64512
 neighbor 10.200.1.1 description TGW
 neighbor 10.200.1.1 update-source eth1
 address-family ipv4 unicast
  network 10.0.1.0/24
  neighbor 10.200.1.1 activate
  neighbor 10.200.1.1 soft-reconfiguration inbound
 exit-address-family
!
line vty
