frr version 9.0
frr defaults traditional
hostname aws-edge-2
no ipv6 forwarding
!
router bgp 64512
 bgp router-id 169.254.20.2
 neighbor 169.254.20.1 remote-as 65001
 neighbor 169.254.20.1 description Customer-Path-B
 neighbor 10.200.1.2 remote-as 64512
 neighbor 10.200.1.2 description VPC-GW-iBGP
 neighbor 10.200.1.2 update-source eth2
 !
 address-family ipv4 unicast
  neighbor 169.254.20.1 activate
  neighbor 169.254.20.1 soft-reconfiguration inbound
  neighbor 10.200.1.2 activate
  neighbor 10.200.1.2 next-hop-self
  neighbor 10.200.1.2 soft-reconfiguration inbound
 exit-address-family
!
line vty
