frr version 9.0
frr defaults traditional
hostname on-prem-router
no ipv6 forwarding
!
router bgp 65001
 bgp router-id 169.254.10.1
 neighbor 169.254.10.2 remote-as 64512
 neighbor 169.254.10.2 description AWS-Edge-1-Path-A
 neighbor 169.254.20.2 remote-as 64512
 neighbor 169.254.20.2 description AWS-Edge-2-Path-B
 !
 address-family ipv4 unicast
  network 10.100.0.0/24
  maximum-paths 2
  neighbor 169.254.10.2 activate
  neighbor 169.254.10.2 soft-reconfiguration inbound
  neighbor 169.254.10.2 next-hop-self
  neighbor 169.254.20.2 activate
  neighbor 169.254.20.2 soft-reconfiguration inbound
  neighbor 169.254.20.2 next-hop-self
 exit-address-family
!
line vty
