frr version 9.0
frr defaults traditional
hostname vpc-gw
no ipv6 forwarding
!
router bgp 64512
 bgp router-id 10.200.0.2
 neighbor 10.200.0.1 remote-as 64512
 neighbor 10.200.0.1 description AWS-Edge-1
 neighbor 10.200.0.1 update-source eth1
 neighbor 10.200.1.1 remote-as 64512
 neighbor 10.200.1.1 description AWS-Edge-2
 neighbor 10.200.1.1 update-source eth2
 !
 address-family ipv4 unicast
  network 10.0.0.0/24
  maximum-paths ibgp 2
  neighbor 10.200.0.1 activate
  neighbor 10.200.0.1 soft-reconfiguration inbound
  neighbor 10.200.1.1 activate
  neighbor 10.200.1.1 soft-reconfiguration inbound
 exit-address-family
!
line vty
